# Generated by Django 2.1.7 on 2019-03-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_rater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressurerecord',
            name='comment',
            field=models.CharField(default='', max_length=512),
        ),
    ]
